Repository personull-mfc/mfc-member, pull requests merged in 2024-06, with the labels that each got.

#32 로그인 시 파트너 코드 반환 로직 수정
  src/main/java/com/mfc/memberservice/member/application/AuthServiceImpl.java
  src/main/java/com/mfc/memberservice/member/application/MemberServiceImpl.java
  src/main/java/com/mfc/memberservice/member/dto/resp/SignInRespDto.java
  src/main/java/com/mfc/memberservice/member/presentation/AuthController.java
  src/main/java/com/mfc/memberservice/member/vo/resp/SignInRespVo.java
Labels: 🐛 bug, 🌓Backend

#34 스타일 관련 API 구현 및 리팩토링
  src/main/java/com/mfc/memberservice/member/application/AuthServiceImpl.java
  src/main/java/com/mfc/memberservice/member/application/MemberService.java
  src/main/java/com/mfc/memberservice/member/application/MemberServiceImpl.java
  src/main/java/com/mfc/memberservice/member/application/StyleService.java
  src/main/java/com/mfc/memberservice/member/application/StyleServiceImpl.java
  src/main/java/com/mfc/memberservice/member/domain/FavoriteStyle.java
  src/main/java/com/mfc/memberservice/member/domain/Style.java
  src/main/java/com/mfc/memberservice/member/dto/resp/FavoriteStyleDto.java
  src/main/java/com/mfc/memberservice/member/dto/resp/FavoriteStyleRespDto.java
  src/main/java/com/mfc/memberservice/member/dto/resp/StyleDto.java
  src/main/java/com/mfc/memberservice/member/dto/resp/StyleListRespDto.java
  src/main/java/com/mfc/memberservice/member/infrastructure/CustomMemberRepository.java
  src/main/java/com/mfc/memberservice/member/infrastructure/CustomRepository.java
  src/main/java/com/mfc/memberservice/member/infrastructure/CustomRepositoryImpl.java
  src/main/java/com/mfc/memberservice/member/infrastructure/FavoriteStyleRepository.java
  src/main/java/com/mfc/memberservice/member/infrastructure/MemberRepository.java
  src/main/java/com/mfc/memberservice/member/infrastructure/StyleRepository.java
  src/main/java/com/mfc/memberservice/member/presentation/MemberController.java
  src/main/java/com/mfc/memberservice/member/presentation/StyleController.java
  src/main/java/com/mfc/memberservice/member/vo/resp/FavoriteStyleRespVo.java
  src/main/java/com/mfc/memberservice/member/vo/resp/FavoriteStyleVo.java
  src/main/java/com/mfc/memberservice/member/vo/resp/StyleListRespVo.java
  src/main/java/com/mfc/memberservice/member/vo/resp/StyleVo.java
Labels: 💫 feat, ♻️ refactor, 🌓Backend

#37 Auth-Service 분리 (1)
  build.gradle
  src/main/java/com/mfc/memberservice/common/config/KafkaConfig.java
  src/main/java/com/mfc/memberservice/member/application/AuthServiceImpl.java
  src/main/java/com/mfc/memberservice/member/application/KafkaConsumer.java
  src/main/java/com/mfc/memberservice/member/application/MemberServiceImpl.java
  src/main/java/com/mfc/memberservice/member/application/PartnerService.java
  src/main/java/com/mfc/memberservice/member/application/PartnerServiceImpl.java
  src/main/java/com/mfc/memberservice/member/domain/Career.java
  src/main/java/com/mfc/memberservice/member/domain/Partner.java
  src/main/java/com/mfc/memberservice/member/domain/Sns.java
  src/main/java/com/mfc/memberservice/member/dto/kafka/DeleteProfileDto.java
  src/main/java/com/mfc/memberservice/member/dto/kafka/InsertProfileDto.java
  src/main/java/com/mfc/memberservice/member/dto/resp/SignInRespDto.java
  src/main/java/com/mfc/memberservice/member/infrastructure/CareerRepository.java
  src/main/java/com/mfc/memberservice/member/infrastructure/PartnerRepository.java
  src/main/java/com/mfc/memberservice/member/infrastructure/SnsRepository.java
  src/main/java/com/mfc/memberservice/member/presentation/PartnerController.java
  src/main/java/com/mfc/memberservice/member/vo/resp/SignInRespVo.java
Labels: 💫 feat, ♻️ refactor, 🌓Backend

#38 feat: requestHistory 생성 위해 필요한 정보 카프카를 통해 전달
  src/main/java/com/mfc/memberservice/member/application/KafkaConsumer.java
Labels: 💫 feat, 🌓Backend

#43 auth 관련 로직 제거 및 리팩토링
  build.gradle
  src/main/java/com/mfc/memberservice/common/config/ApplicationConfig.java
  src/main/java/com/mfc/memberservice/common/config/SecurityConfig.java
  src/main/java/com/mfc/memberservice/common/exception/BaseExceptionHandler.java
  src/main/java/com/mfc/memberservice/common/jwt/JwtTokenProvider.java
  src/main/java/com/mfc/memberservice/common/sms/SmsUtil.java
  src/main/java/com/mfc/memberservice/member/application/AuthService.java
  src/main/java/com/mfc/memberservice/member/application/AuthServiceImpl.java
  src/main/java/com/mfc/memberservice/member/application/KafkaConsumer.java
  src/main/java/com/mfc/memberservice/member/application/MemberService.java
  src/main/java/com/mfc/memberservice/member/application/MemberServiceImpl.java
  src/main/java/com/mfc/memberservice/member/application/PartnerService.java
  src/main/java/com/mfc/memberservice/member/application/PartnerServiceImpl.java
  src/main/java/com/mfc/memberservice/member/application/UserServiceImpl.java
  src/main/java/com/mfc/memberservice/member/domain/Member.java
  src/main/java/com/mfc/memberservice/member/domain/PriceOption.java
  src/main/java/com/mfc/memberservice/member/dto/req/ModifyMemberReqDto.java
  src/main/java/com/mfc/memberservice/member/dto/req/OptionReqDto.java
  src/main/java/com/mfc/memberservice/member/dto/req/SignInReqDto.java
  src/main/java/com/mfc/memberservice/member/dto/req/SignUpReqDto.java
  src/main/java/com/mfc/memberservice/member/dto/req/SmsReqDto.java
  src/main/java/com/mfc/memberservice/member/dto/resp/OptionDto.java
  src/main/java/com/mfc/memberservice/member/dto/resp/OptionListRespDto.java
  src/main/java/com/mfc/memberservice/member/infrastructure/CustomRepository.java
  src/main/java/com/mfc/memberservice/member/infrastructure/CustomRepositoryImpl.java
  src/main/java/com/mfc/memberservice/member/infrastructure/MemberRepository.java
  src/main/java/com/mfc/memberservice/member/infrastructure/PriceOptionRepository.java
  src/main/java/com/mfc/memberservice/member/infrastructure/SmsRepository.java
  src/main/java/com/mfc/memberservice/member/presentation/AuthController.java
  src/main/java/com/mfc/memberservice/member/presentation/MemberController.java
  src/main/java/com/mfc/memberservice/member/presentation/PartnerController.java
  src/main/java/com/mfc/memberservice/member/vo/req/ModifyPasswordReqVo.java
  src/main/java/com/mfc/memberservice/member/vo/req/OptionReqVo.java
  src/main/java/com/mfc/memberservice/member/vo/req/SignInReqVo.java
  src/main/java/com/mfc/memberservice/member/vo/req/SignUpReqVo.java
  src/main/java/com/mfc/memberservice/member/vo/req/SmsReqVo.java
  src/main/java/com/mfc/memberservice/member/vo/resp/OptionListRespVo.java
  src/main/java/com/mfc/memberservice/member/vo/resp/OptionVO.java
Labels: ♻️ refactor, 🌓Backend

#48 스타일 별 파트너 id 목록 조회 API 구현
  src/main/java/com/mfc/memberservice/member/application/PartnerService.java
  src/main/java/com/mfc/memberservice/member/application/PartnerServiceImpl.java
  src/main/java/com/mfc/memberservice/member/dto/resp/PartnersByStyleRespDto.java
  src/main/java/com/mfc/memberservice/member/infrastructure/FavoriteStyleRepository.java
  src/main/java/com/mfc/memberservice/member/presentation/PartnerController.java
  src/main/java/com/mfc/memberservice/member/vo/resp/PartnersByStyleRespVo.java
Labels: 💫 feat, 🌓Backend

#49 프로필 이미지 변경 시 에러 수정
  src/main/java/com/mfc/memberservice/member/application/UserServiceImpl.java
Labels: 🐛 bug, 🌓Backend

#51 홈 화면 관련 API 구현
  src/main/java/com/mfc/memberservice/member/application/PartnerService.java
  src/main/java/com/mfc/memberservice/member/application/PartnerServiceImpl.java
  src/main/java/com/mfc/memberservice/member/dto/resp/PartnerProfileListRespDto.java
  src/main/java/com/mfc/memberservice/member/dto/resp/ProfilesDto.java
  src/main/java/com/mfc/memberservice/member/infrastructure/FavoriteStyleRepository.java
  src/main/java/com/mfc/memberservice/member/infrastructure/PartnerRepository.java
  src/main/java/com/mfc/memberservice/member/presentation/PartnerController.java
  src/main/java/com/mfc/memberservice/member/vo/resp/PartnerProfileListRespVo.java
  src/main/java/com/mfc/memberservice/member/vo/resp/ProfilesVo.java
Labels: 💫 feat, 🌓Backend

#53 파트너 프로필 집계 구현
  src/main/java/com/mfc/memberservice/member/application/KafkaConsumer.java
  src/main/java/com/mfc/memberservice/member/application/KafkaProducer.java
  src/main/java/com/mfc/memberservice/member/application/MemberServiceImpl.java
  src/main/java/com/mfc/memberservice/member/dto/kafka/PartnerSummaryDto.java
Labels: 💫 feat, ♻️ refactor, 🌓Backend

#55 파트너 랭킹 구현
  build.gradle
  src/main/java/com/mfc/memberservice/MemberserviceApplication.java
  src/main/java/com/mfc/memberservice/common/client/BatchClient.java
  src/main/java/com/mfc/memberservice/common/client/PartnerRankingResponse.java
  src/main/java/com/mfc/memberservice/member/application/PartnerService.java
  src/main/java/com/mfc/memberservice/member/application/PartnerServiceImpl.java
  src/main/java/com/mfc/memberservice/member/dto/req/PartnerRankingReqDto.java
  src/main/java/com/mfc/memberservice/member/dto/req/PartnerSummaryReqDto.java
  src/main/java/com/mfc/memberservice/member/dto/resp/FavoriteStylesDto.java
  src/main/java/com/mfc/memberservice/member/dto/resp/PartnerRankingDto.java
  src/main/java/com/mfc/memberservice/member/dto/resp/PartnerRankingRespDto.java
  src/main/java/com/mfc/memberservice/member/dto/resp/StyleValueDto.java
  src/main/java/com/mfc/memberservice/member/infrastructure/CustomRepository.java
  src/main/java/com/mfc/memberservice/member/infrastructure/CustomRepositoryImpl.java
  src/main/java/com/mfc/memberservice/member/presentation/PartnerController.java
  src/main/java/com/mfc/memberservice/member/vo/resp/FavoriteStylesVo.java
  src/main/java/com/mfc/memberservice/member/vo/resp/PartnerRankingRespVo.java
  src/main/java/com/mfc/memberservice/member/vo/resp/PartnerRankingVo.java
  src/main/java/com/mfc/memberservice/member/vo/resp/StyleValueVo.java
Labels: 💫 feat, 🌓Backend
